# Krikey's Dataset - Data Analysis
In this notebook, we use the dataset provided by the krikey team and first perform exploratory data analysis to understand the data better. Futher, we go about with a deeper-dive analysis. Each deep-dive is started by posing a question that might is deemed to be useful for the business. All along this notebook, clear description is provided as and when required. Table below is organization of the work carried out in this notebook as part of the data analysis.

## Table of Contents
1. Import Python libraries
2. Load data files
3. Descriptive data analysis
4. Exploratory data analysis
5. Deep-dive data analysis

***

## Import Python libraries
In this section, we import libraries as per requirement and check if the libraries are loading correctly by printing out the version of the library that is loaded.

In [12]:
# Manage files/folders
import os

# Data processing analysis library
import pandas as pd 

# Pandas profiling library - A faster, effecient way in profiling the data
from pandas_profiling import ProfileReport

# Data viz library
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_bokeh

# Setting default viz options for pandas 
pd.set_option('plotting.backend', 'pandas_bokeh')

In [8]:
# check library versions
print(f'>>> Pandas version:{pd.__version__}')
print(f'>>> Seaborn version:{sns.__version__}')

# check pandas_bokeh
pandas_bokeh.output_notebook()

>>> Pandas version:1.4.1
>>> Seaborn version:0.11.2

***

## Load Data & Check for data quality issues
In this section, we load the data from the set of csv files provided by krikey team. Further, we check the data for any data quality issues. These preliminary data quality checks will help us document any assumptions (or limitations concerning the data) before starting with the data analysis. This step will assist us in developing sensible business questions in the later stages. Our understanding of data in this section is documented in the **Notes on Data and Quality** sub-section.

### Load Data
Data is provided in 4 different csv files. Each csv file has specific information as below:

1. **watchedVideo**: This contains all occurrences of the watchedVideo event.
2. **users**: This table contains the registered users
3. **videos**: This table contains all created videos
4. **feeds**: This contains the feeds the videos are served on

In [49]:
# Set PATH for data files
PATH_DATA    = os.path.join(os.getcwd(),'data')
FILE_USERS   = os.path.join(PATH_DATA,'users.csv')
FILE_VIDEOS  = os.path.join(PATH_DATA,'videos.csv')
FILE_FEEDS   = os.path.join(PATH_DATA,'feeds.csv')
FILE_WATCHED = os.path.join(PATH_DATA,'watchedVideo.csv')

print('|------------------------------------------------------------------|')
print(f' PATH to DATA folder: {PATH_DATA}')
print(f'     - PATH to csv file: {FILE_USERS}')
print(f'     - PATH to csv file: {FILE_VIDEOS}')
print(f'     - PATH to csv file: {FILE_FEEDS}')
print(f'     - PATH to csv file: {FILE_WATCHED}')
print('|------------------------------------------------------------------|')

|------------------------------------------------------------------|
 PATH to DATA folder: /home/jovyan/work/data
     - PATH to csv file: /home/jovyan/work/data/users.csv
     - PATH to csv file: /home/jovyan/work/data/videos.csv
     - PATH to csv file: /home/jovyan/work/data/feeds.csv
     - PATH to csv file: /home/jovyan/work/data/watchedVideo.csv
|------------------------------------------------------------------|

In [50]:
# Load "users" data file
df_users = pd.read_csv(FILE_USERS, index_col=0)
print(f' >>> Loaded: {FILE_USERS} file has {df_users.shape[0]} rows and {df_users.shape[1]} columns')

# Load "videos" data file
df_videos = pd.read_csv(FILE_VIDEOS, index_col=0)
print(f' >>> Loaded: {FILE_VIDEOS} file has {df_videos.shape[0]} rows and {df_videos.shape[1]} columns')

# Load "feeds" data file
df_feeds = pd.read_csv(FILE_FEEDS, index_col=0)
print(f' >>> Loaded: {FILE_FEEDS} file has {df_feeds.shape[0]} rows and {df_feeds.shape[1]} columns')

# Load "watchedvideos" data file
df_watched = pd.read_csv(FILE_WATCHED, index_col=0)
print(f' >>> Loaded: {FILE_WATCHED} file has {df_watched.shape[0]} rows and {df_watched.shape[1]} columns')

 >>> Loaded: /home/jovyan/work/data/users.csv file has 1000 rows and 4 columns
 >>> Loaded: /home/jovyan/work/data/videos.csv file has 5000 rows and 10 columns
 >>> Loaded: /home/jovyan/work/data/feeds.csv file has 10 rows and 2 columns
 >>> Loaded: /home/jovyan/work/data/watchedVideo.csv file has 50000 rows and 8 columns

### Check Data Quality

In [51]:
# Check - missing values in users, videos, feeds, watchedVideo
print(f' >> No. of Missing Values in users.csv: {df_users.isnull().sum().sum()}')
print(f' >> No. of Missing Values in videos.csv: {df_videos.isnull().sum().sum()}')
print(f' >> No. of Missing Values in feeds.csv: {df_feeds.isnull().sum().sum()}')
print(f' >> No. of Missing Values in watchedVideo.csv: {df_watched.isnull().sum().sum()}')

 >> No. of Missing Values in users.csv: 0
 >> No. of Missing Values in videos.csv: 0
 >> No. of Missing Values in feeds.csv: 0
 >> No. of Missing Values in watchedVideo.csv: 0

In [52]:
# Check - Duplicate Rows in users, videos, feeds, watchedVideo
print(f' >> No. of Duplicate Rows in users.csv: {df_users.duplicated().sum()}')
print(f' >> No. of Duplicate Rows in videos.csv: {df_videos.duplicated().sum()}')
print(f' >> No. of Duplicate Rows in feeds.csv: {df_feeds.duplicated().sum()}')
print(f' >> No. of Duplicate Rows in watchedVideo.csv: {df_watched.duplicated().sum()}')

 >> No. of Duplicate Rows in users.csv: 0
 >> No. of Duplicate Rows in videos.csv: 0
 >> No. of Duplicate Rows in feeds.csv: 0
 >> No. of Duplicate Rows in watchedVideo.csv: 0

#### Notes on Data and Quality
- **4 csv files** are loaded as **4 different dataframes** using pandas module.
- Every file has different no. of rows and columns as shown above. 
- There are **NO** **missing values** or **duplicated entries** in the data to start with. This is a good starting point as we don't have to consider any assumption (E.g: to handle missing values etc.,) before starting with the data analysis.

P.S: 
- In the interest of time, for this challenge, we don't look into data quality issues at discrete feature level.

***

## Descriptive Data Analysis
In this section, we perform descriptive analysis on the data being loaded into 4 different dataframes. Futher, our understanding about the data from descriptive analysis is documented in **Notes on Descriptive Analysis** sub-section.

### Users data
We first look into the first few entries of the users data, identify datatypes of different features, and finally create a table of descriptive statistics on the features of the data.

In [54]:
# Display first 5 rows in users data
df_users.head()

,id,created_at,class,coordinates
0,37e369a8-4477-4d5d-acd7-4e3b8059586e,2021-03-23 00:24:53,Creator,"('36.76775', '2.95924')"
1,27cf0bb6-3488-4662-916d-3ad04eeec9ca,2021-04-09 19:55:07,Viewer,"('43.71032', '-1.05366')"
2,5ebd5e12-ba2a-4bf9-b7e4-92ad24711cd4,2021-04-08 21:48:45,Super Gamer,"('51.26', '-2.1875')"
3,30986592-0cbf-43bb-83ed-7501ab3bd373,2021-05-15 00:45:51,Creator,"('40.65538', '-74.38987')"
4,25b49125-34d1-4694-a4a9-8415bcc3567b,2021-07-05 04:08:53,Viewer,"('35.61452', '-88.81395')"

In [55]:
# Datatypes of users data
df_users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1000 non-null   object
 1   created_at   1000 non-null   object
 2   class        1000 non-null   object
 3   coordinates  1000 non-null   object
dtypes: object(4)
memory usage: 39.1+ KB

In [57]:
# Descriptive Statis on users data
df_users.describe(include='object')

,id,created_at,class,coordinates
count,1000,1000,1000,1000
unique,1000,1000,5,626
top,37e369a8-4477-4d5d-acd7-4e3b8059586e,2021-03-23 00:24:53,Gamer,"('-6.25', '38.66667')"
freq,1,1,213,6

### Videos data
In Videos data, we first look into the first few entries of the data, identify datatypes of different attributes, and finally create a table of descriptive statistics on the features of the data.

In [58]:
# Display first 5 rows in videos data
df_videos.head()

,id,attribute_id,music_id,animation_id,duration,creator,created_at,num_shares,game_id,is_ar
0,6e884071-8c0e-4782-aa40-e0fd78243360,4712e9e6-bef1-4646-b21e-ca5336901bf9,4ee0de5b-e27f-4d73-a3c6-52cf26e36c54,17dab81c-6180-4a4b-b539-91978a726cfd,5.34,73ec1ac2-d148-45ac-94a8-9bdff51730d7,2021-08-04 10:42:39,12,8bd4c7be-fe87-45ad-990d-d131cd3d9c77,True
1,ac90ff16-24b4-46bc-ae72-2da847f9e6c9,4f91d2b6-bf42-4d3f-a8e8-acc3b07f647e,4ee0de5b-e27f-4d73-a3c6-52cf26e36c54,6d7a0545-0bca-4bf4-a306-931e57d8ffe2,3.88,0230f9af-e89f-4886-8322-52a38eaf991c,2021-11-27 10:06:43,3,6ca0f645-a16b-42b0-9dc2-2ae952c83591,True
2,fb5eaf0d-e72c-4523-b5c5-4d9c323cef5f,80f5b187-f6e6-40f2-9b6e-fe62b67049a8,d53234f4-1efb-4299-97c1-11658118cba5,716c02df-bd3a-41c9-b2be-86fb74ff3255,5.15,fbf93fbf-a935-436f-8516-8acb863e779f,2021-02-26 04:18:53,4,6ca0f645-a16b-42b0-9dc2-2ae952c83591,True
3,bbf89dcb-7fbd-439d-9a7d-36ef7a1c2aa3,02b2b662-1b39-4d91-9417-dddc9451d8e1,19e4db13-d854-4913-a8ca-3612ee1a6071,b7bd5204-2976-4eb0-ab71-508a848bc325,6.50,f7a2adb8-44d7-4408-a2a9-3a593fc6d626,2021-11-27 02:08:02,9,8bd4c7be-fe87-45ad-990d-d131cd3d9c77,False
4,4c613ec6-fa6f-47e8-b4ab-658e2f6a644d,06c496ee-e884-42f9-ba39-010a66ed5296,b5b679a5-e769-4d95-82a6-f75e439b1ef9,17dab81c-6180-4a4b-b539-91978a726cfd,4.38,d9f9538f-1b7e-4f35-805d-924b309d75d8,2021-11-17 11:06:32,14,2609b6b5-3a08-451e-bce5-75fe506559d2,False

In [59]:
# Datatypes of videos data
df_videos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5000 non-null   object
 1   attribute_id  5000 non-null   object
 2   music_id      5000 non-null   object
 3   animation_id  5000 non-null   object
 4   duration      5000 non-null   float64
 5   creator       5000 non-null   object
 6   created_at    5000 non-null   object
 7   num_shares    5000 non-null   int64
 8   game_id       5000 non-null   object
 9   is_ar         5000 non-null   bool
dtypes: bool(1), float64(1), int64(1), object(7)
memory usage: 395.5+ KB

In [64]:
# Descriptive Statis on videos data - Categorical
df_videos.describe(include='object')

,id,attribute_id,music_id,animation_id,creator,created_at,game_id
count,5000,5000,5000,5000,5000,5000,5000
unique,5000,11,10,15,992,5000,5
top,6e884071-8c0e-4782-aa40-e0fd78243360,25e7fab9-abfb-4a74-a8cb-c3adbc6e3531,c3721b09-6896-465a-8e13-4d73efd06874,d167d0af-a662-48ad-bb39-5aa306fc8141,ddfeab0f-274a-4cab-86c2-873cbd8e485e,2021-08-04 10:42:39,8bd4c7be-fe87-45ad-990d-d131cd3d9c77
freq,1,483,550,359,12,1,1021

In [67]:
# Descriptive Statis on videos data - Numerical
df_videos.describe(exclude='object')

           duration   num_shares is_ar
count   5000.000000  5000.000000  5000
unique          NaN          NaN     2
top             NaN          NaN  True
freq            NaN          NaN  2528
mean       4.536508     9.848800   NaN
std        1.402695     5.995526   NaN
min        2.100000     0.000000   NaN
25%        3.330000     5.000000   NaN
50%        4.555000    10.000000   NaN
75%        5.720000    15.000000   NaN
max        7.000000    20.000000   NaN

### Feeds data
In Feeds data too, we first look into the first few entries of the data, identify datatypes of different attributes, and finally create a table of descriptive statistics on the features of the data.

In [65]:
# Display first 5 rows in feeds data
df_feeds.head()

                                     id     name
0  27a87df4-da75-451f-b8f6-af9dd0a4ee00    music
1  42568c8a-efbe-4293-81a3-513e33094ade  fashion
2  6894af29-56cc-4b4a-8ee6-be9b3cb3e7f1   sports
3  c9d59470-c4ee-43ff-831d-b52508c8d848    games
4  582520b2-b30a-4ecb-b1b4-1806672fcfc4   travel

In [66]:
# Datatypes of feeds data
df_feeds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     object
 1   name    10 non-null     object
dtypes: object(2)
memory usage: 240.0+ bytes

In [68]:
# Descriptive Statis on feeds data
df_feeds.describe(include='object')

                                          id   name
count                                     10     10
unique                                    10     10
top     27a87df4-da75-451f-b8f6-af9dd0a4ee00  music
freq                                       1      1

### WatchedVideos data
In watched videos data file, we first look into the first few entries of the data, identify datatypes of different attributes, and finally create a table of descriptive statistics on the features of the data.

In [69]:
# Display first 5 rows in watched videos data
df_watched.head()

,coordinates,os,duration,videoId,userId,appVersion,dateTime,feedId
0,"(Decimal('14.439490'), Decimal('105.291233'))",iOS,3.95,722e110c-2f81-46aa-9c25-4d26fd77519f,317a2bc3-5f95-4d35-9a94-1f2f38424c4f,2.2.2,2021-08-04 09:39:07,30134b9e-1b79-43fb-b0c5-373af9237b2c
1,"(Decimal('40.866935'), Decimal('-73.845013'))",iOS,5.95,cc10d153-37f9-42b5-8d78-2365908acf2b,db031c3d-69e4-4c06-91fe-e9be0a3c173c,2.2.1,2021-07-06 16:32:10,8078efe7-5bae-4528-9a66-b85904cc73ac
2,"(Decimal('48.666850'), Decimal('9.359456'))",iOS,0.69,7f3f7fce-f2ec-4dfd-bac8-92dc7865a365,8fb18b66-f548-42a7-b394-c1be963cac29,2.2.0,2021-12-06 01:42:02,6894af29-56cc-4b4a-8ee6-be9b3cb3e7f1
3,"(Decimal('5.172365'), Decimal('-74.439009'))",Android,2.81,8ffc47e3-32ce-4d24-a990-9baac556603b,960fb90e-eddc-478a-a64a-04b9dded3a05,2.1.2,2021-12-04 21:02:50,42568c8a-efbe-4293-81a3-513e33094ade
4,"(Decimal('4.063707'), Decimal('9.606159'))",iOS,5.88,47e70477-7511-4bd0-801b-1651f951002f,1ce0c003-25e7-473f-8796-0fe04d6c275c,2.1.2,2021-11-28 16:12:39,582520b2-b30a-4ecb-b1b4-1806672fcfc4

In [70]:
# Datatypes of watched videos data
df_watched.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   coordinates  50000 non-null  object
 1   os           50000 non-null  object
 2   duration     50000 non-null  float64
 3   videoId      50000 non-null  object
 4   userId       50000 non-null  object
 5   appVersion   50000 non-null  object
 6   dateTime     50000 non-null  object
 7   feedId       50000 non-null  object
dtypes: float64(1), object(7)
memory usage: 3.4+ MB

### Notes on Descriptive analysis
- **users** data
    - No. of attributes = 4
    - All the attributes by default are object datatypes. In contrast, `created_at` should be **datetime** datatype and `coordinates` should be longitude, latitude float attributes. 
    - Unique identified `id` has 1000 unique values. This means, there are around 1000 unique users. 
- **videos** data
    - No. of attributes = 10
    - Here too, `created_at` should be **datetime** datatype. 
    - Unique identified `id` has 5000 unique values. This means, there are around 5000 unique videos. 
- **feeds** data
    - No. of attributes = 2
    - Unique identified `id` has 10 unique values. This means, there are around 10 unique feeds possible. 
- **watchedVideo** data
    - No. of attributes = 8
    - Here too, `coordinates` should be longitude, latitude 2 float attributes, and `dateTime` should be **datatime** datatype.
    - There are 50000 videos that were watched. This data might include videos that had multiple views.

****

## Exploratory Data Analysis

***

## Deep-Dive Data Analysis

***